import { Providers } from "@/contexts/provideres";
import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "../styles/globals.css";
import Head from "./head";

export const dosis = Dosis({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "IFoverflow",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  signup: React.ReactNode;
  questions: React.ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="pt-br">
      <Head />
      <body className={`${dosis.className} bg-neutral-100`}>
        <Providers>
          <Toaster
            position="top-center"
            reverseOrder={false}
            gutter={8}
            containerClassName=""
            containerStyle={{}}
            toastOptions={{
              // Define default options
              className: "",
              duration: 5000,
              style: {
                background: "#fff",
                color: "#000",
              },
              // Default options for specific types
              success: {
                duration: 3000,
                iconTheme: {
                  primary: "green",
                  secondary: "#fff",
                },
              },
              error: {
                duration: 3000,
                iconTheme: {
                  primary: "red",
                  secondary: "#fff",
                },
              },
            }}
          />
          {props.children}
          {props.signup}
        </Providers>
      </body>
    </html>
  );
}
